PREFIX dc: <http://purl.org/dc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX osm: <http://www.metaphacts.com/ontologies/osm#>
PREFIX gs-api: <https://w3id.org/demeter/agri/ext/gaiasense#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX fiware: <https://uri.fiware.org/ns/data-models#>
PREFIX geo84: <http://www.w3.org/2003/01/geo/wgs84_pos#>
SELECT * WHERE {
   BIND("2022-08-25"^^xsd:date as ?inputfromdate)
   BIND("2022-08-26"^^xsd:date as ?inputtodate)
   #BIND("37.9157894"^^xsd:decimal as ?inputlong)
   #BIND("22.8124069"^^xsd:decimal as ?inputlat)
   ##default values for other inputs as below
   #BIND("nplwrh1, nplwrh2, wsht30_rh, uv, pyranometer, pressure, velocity, gust, vr_winddir, rain, nplwtemp1, nplwtemp2, wsht30_temp, nplwlw1, nplwlw"^^xsd:string as ?inputsensors)
   #BIND("10"^^xsd:integer as ?inputlimit)
   #BIND("205"^^xsd:integer as ?inputlocationid)
   #BIND("100"^^xsd:integer as ?inputradius)
   #BIND("0"^^xsd:integer as ?inputoffset)
   #BIND("asc"^^xsd:string as ?inputorder)
  SERVICE <http://www.metaphacts.com/ontologies/platform/repository/federation#gaiasenseMeasurements> {
## inputs
    ?results fiware:validFrom ?inputfromdate .
    ?results fiware:validTo ?inputtodate .
    #?results gs-api:longInput ?inputlong .
    #?results gs-api:latInput ?inputlat .
    ##default values
    #?results sosa:madeBySensor ?inputsensors .
    #?results gs-api:limit ?inputlimit .
    #?results gs-api:locationIdInput ?inputlocationid .
    #?results gs-api:radiusInput ?inputradius .
    #?results gs-api:offset ?inputoffset .
    #?results gs-api:orderBy ?inputorder .
    
## outputs    
    ?results sosa:resultTime ?m_date .
    ?results gs-api:nplwrh1 ?nplwrh1 .
    ?results gs-api:nplwrh2 ?nplwrh2 .
    ?results gs-api:wsht30_rh ?wsht30_rh .
    ?results gs-api:uv ?uv .
    #?results gs-api:pyranometer ?pyranometer .
    #?results gs-api:pressure ?pressure .
    #?results gs-api:velocity ?velocity .
    #?results gs-api:gust ?gust .
    #?results gs-api:vr_winddir ?vr_winddir .
    #?results gs-api:rain ?rain .
    #?results gs-api:nplwtemp1 ?nplwtemp1 .
    #?results gs-api:nplwtemp2 ?nplwtemp2 .
    #?results gs-api:wsht30_temp ?wsht30_temp .
    #?results gs-api:nplwlw1 ?nplwlw1 .
  }
  SERVICE <http://www.metaphacts.com/ontologies/platform/repository/federation#gaiasenseMeasurementsLocation> {
## inputs
    ?results fiware:validFrom ?inputfromdate .
    ?results fiware:validTo ?inputtodate .
    #?results gs-api:longInput ?inputlong .
    #?results gs-api:latInput ?inputlat .
    ##default values
    #?results sosa:madeBySensor ?inputsensors .
    #?results gs-api:limit ?inputlimit .
    #?results gs-api:locationIdInput ?inputlocationid .
    #?results gs-api:radiusInput ?inputradius .
    #?results gs-api:offset ?inputoffset .
    #?results gs-api:orderBy ?inputorder .
    
## outputs
    ?results dc:identifier ?locationIdOutput .
    ?results geo84:long ?longitud .
    ?results geo84:lat ?latitude .
    ?results geo84:alt ?altitude .
    ?results fiware:name ?name .
    ?results gs-api:toponym ?toponym .
    ?results fiware:status ?status .
  }
 } LIMIT 100